### ISSUE TITLE
NPE Error on /market.

### ISSUE THREAD

**Issue by ghost** [Dasfaust/GlobalMarket#60]
Hello again,

I've since installed the proper version of ProtocolLib and the Redis server. The Redis server installed and started up properly, but now I get this error when doing /market;

---

http://pastebin.com/gRWBzu0F

**Comment by Dasfaust** [comment]
Looks like the part of the plugin that handles menus is null, so it didn't load all the way. Check your server log for messages/exceptions from GlobalMarket on startup.

**Comment by AnodyneEntity** [comment]
Thank you for replying as fast as you do, this is the error GlobalMarket throws on startup. Might just be a misconfiguration on my part, seems like it's either not enough memory, or invalid password;

---
http://pastebin.com/4RzTZXjD

**Comment by Dasfaust** [comment]
Hmm, I think this happens since FML replaces the default Java SecurityManager. Try this: make a file called security.policy in your server's root directory with this as the contents:

```
grant {
    permission javax.management.MBeanTrustPermission "register";
};
```

save it, and add `-Djava.security.policy=security.policy` to your server's startup arguments. That should work. Don't know if this will be a permanent solution though.

Your command should look something like this: `java -Xmx1024m -Djava.security.policy=security.policy -jar KCauldron-1.7.10-1448.133-server.jar`

**Comment by AnodyneEntity** [comment]
Did as you said, still getting the same NPE error.
