### ISSUE TITLE
DUPE Glitch

### ISSUE THREAD

**Issue by madtomic** [Dasfaust/GlobalMarket#77]
Click one item in, take a stack of 64 and click the empty storage and it will fill the one to 64. click that stack listed and you get 64 new items for free. This 2.0 is very bad.

**Comment by DraksterAU** [comment]
@madtomic 2.0.0 isn't ready for use by anyone yet. You should still be using 1.3 or disable the storage stuff.

**Comment by Dasfaust** [comment]
A little downtime in development... but, which build? Are you using the stock system or is it disabled?

Trying to understand, put 1 item in a slot, put 64 of the same item in another slot? It'll combine slots of the same item to conserve space. That means you have 65 items in storage, and clicking the original slot gets your stack of 64 back. I don't see a dupe happening here.

A video or a gif of what's going on would be extremely useful.

**Comment by Dasfaust** [comment]
Can confirm as fixed in build 24. Thanks to @prozhong. Just for reference, the only way I was able to duplicate this bug was by inserting stacks into a stock slot, having less than the item's max stack size's room left in the stock slot, and inserting more than that via another slot. So say there was a max stock size of 64, and you had 32 items in the slot. Adding 64 to separate slot would duplicate the items. Sorry for the confusion on this.
