### ISSUE TITLE
v2 beta test

### ISSUE THREAD

**Issue by leasoncre** [Dasfaust/GlobalMarket#83]
This server is running CraftBukkit version git-Spigot-b1c1b55-7d330bc (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
GlobalMarket version 2.0.0.27
starting from scratch. testing as OP.

1 . put simply: can't add items to the market
/market create 1 (holding log)
chat error: 'You're already selling this item.'
no console errors, doesn't take the log.

2 . old command:
/market listings
chat error: 'Invalid amount specified: For input string: "ings"'
no console errors, i realize /market pretty much does this now
--similar error:--
/market createserverlisting 1 1
chat error: 'Invalid amount specified: For input string: "serverlisting"'
no console errors

GUI-Based listing/sending/retrieval of items works
3 . stop re-centering the mouse, or add an option to disable this. really annoying for mass listing or most times user convenience is sacrificed. (#moves mouse forever in one direction)

4 . would it be possable to add colored glass panes behind items in your 'stock management' window? or seperate the items listed vs the items stored(&/or received)

 
Q1: i assume posting infinite listings are OP only (or permission node)

F1 . feature: add config option to block the use of market commands in gamemode 1 or 2?

F2 . add shift+right-click to easily move items between market/inventory.

PS. i assume you'll be adding more documentation on the changes/commands/permissions in the future
5. PS. i haven't seen any notification messages when items are sold/bought.

**Comment by Dasfaust** [comment]
1. Fixed in [build 28](http://build.survivorserver.com/job/GlobalMarket%202.0.0/28/).
2. It is indeed now just /market, and it's /market createinf - try /market ? for more info. Updated BukkitDev page, whoops
3. It's Mojang doing that, not me
4. You can't have more than 1 item in an inventory slot, if I understand the question correctly
Q1. Yes, it's on the BukkitDev page
F1. It's on the to-do list!
F2. I'll consider that
For the rest, yes, no notifications at the moment. Documentation will be re-written once it's on spigotmc.org

Thanks for the feedback! Since there is no immediate bug in this issue I'm closing it. Feel free to keep the thread going.

**Comment by leasoncre** [comment]
3 . gotta be a way to fix that, it's so obnoxious.
idea on how to fix that: detect the item removed from the 'chest' and then instead of opening a new chest window, re-update the contents of the 'chest', items are stored in a database anyway correct?
ie: don't change the 'chest' itself, only it's contents. [[can chests be renamed while a player is viewing them?]]

4 . yeah i know that, but i though i'd seen it somewhere before, like 'ghosted' blocks or 2 inv windows shown in layers
-Alternate option: separate the active listings from the received/stored items

**Comment by leasoncre** [comment]
v2.0.0.28 #1 not fixed
